{"name": "Test of failed attempt to login with the wrong fields", "status": "failed", "statusDetails": {"message": "AssertionError: Error message contains wrong text\nassert '{\"code\":404,... не найдена\"}' == '\"message\": \"...ь не найдена\"'\n  - \"message\": \"Учетная запись не найдена\"\n  ?           -\n  + {\"code\":404,\"message\":\"Учетная запись не найдена\"}\n  ? ++++++++++++                                     +", "trace": "self = <tests.test_courier_login.TestCourierLogin object at 0x0000022DD3365B90>, new_courier = (<Response [201]>, ['mvmkupcyos', 'qabqvfkuti', 'zfgxpcjxth']), login_wrong = False\npassword_wrong = True\n\n    @allure.title('Test of failed attempt to login with the wrong fields')\n    @allure.description('Negative test of the endpoint \"Логин курьера в системе\" POST /api/v1/courier/login.'\n                        'Parameterized test, checks impossibility of authorization '\n                        'when any of the mandatory fields is wrong')\n    @pytest.mark.parametrize(\"login_wrong, password_wrong\", [\n        (False, True),  # Тест с верным полем \"login\" и неверным полем \"password\"\n        (True, False)   # Тест с неверным полем \"login\" и верным полем \"password\"\n    ])\n    def test_login_with_any_wrong_field_failed(self, new_courier, login_wrong, password_wrong):\n        login_pass = new_courier[1]\n        payload_login = {\n            \"login\": login_pass[0] if not login_wrong else login_pass[0]+'a',\n            \"password\": login_pass[1] if not password_wrong else login_pass[1]+'b'\n        }\n        response = requests.post(f'{url}/api/v1/courier/login', data=payload_login)\n        assert response.status_code == 404, f'Instead of an error code 404 received code {response.status_code}'\n>       assert response.text == '\"message\": \"Учетная запись не найдена\"', f'Error message contains wrong text'\nE       AssertionError: Error message contains wrong text\nE       assert '{\"code\":404,... не найдена\"}' == '\"message\": \"...ь не найдена\"'\nE         - \"message\": \"Учетная запись не найдена\"\nE         ?           -\nE         + {\"code\":404,\"message\":\"Учетная запись не найдена\"}\nE         ? ++++++++++++                                     +\n\ntests\\test_courier_login.py:56: AssertionError"}, "description": "Negative test of the endpoint \"Логин курьера в системе\" POST /api/v1/courier/login.Parameterized test, checks impossibility of authorization when any of the mandatory fields is wrong", "attachments": [{"name": "stdout", "source": "f2c5c7bc-760c-40f2-8a83-d3dfa6a31956-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login_wrong", "value": "False"}, {"name": "password_wrong", "value": "True"}], "start": 1698833355773, "stop": 1698833356496, "uuid": "3d5f2142-e36d-43bb-91d3-8965e6894aa6", "historyId": "d57eb837b4db049c16b8fa90b3055728", "testCaseId": "67167e8a3582672514a127bcef0528c3", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_with_any_wrong_field_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "Airforce3"}, {"name": "thread", "value": "12480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}