{"name": "Test of failed attempt to login with the missing field", "status": "failed", "statusDetails": {"message": "AssertionError: Error message contains wrong text\nassert '{\"code\":400,...х для входа\"}' == '\"message\":  ...ых для входа\"'\n  - \"message\":  \"Недостаточно данных для входа\"\n  ?           --\n  + {\"code\":400,\"message\":\"Недостаточно данных для входа\"}\n  ? ++++++++++++                                         +", "trace": "self = <tests.test_courier_login.TestCourierLogin object at 0x000001E7A01E5450>, new_courier = (<Response [201]>, ['dqyjwcrbgz', 'difyewxmhy', 'owdrigabpu'])\nmissing_field = 'login'\n\n    @allure.title('Test of failed attempt to login with the missing field')\n    @allure.description('Negative test of the endpoint \"Логин курьера в системе\" POST /api/v1/courier/login.'\n                        'Parameterized test, checks impossibility of authorization '\n                        'when any of the mandatory fields is missing')\n    @pytest.mark.parametrize(\"missing_field\", [\"login\", \"password\"])\n    def test_login_with_any_missing_field_failed(self, new_courier, missing_field):\n        login_pass = new_courier[1]\n        payload = {\n            \"login\": login_pass[0],\n            \"password\": login_pass[1]\n        }\n        del payload[missing_field]\n        response = requests.post(f'{url}/api/v1/courier/login', data=payload)\n        assert response.status_code == 400, f'Instead of an error code 400 received code {response.status_code}'\n>       assert response.text == '\"message\":  \"Недостаточно данных для входа\"', f'Error message contains wrong text'\nE       AssertionError: Error message contains wrong text\nE       assert '{\"code\":400,...х для входа\"}' == '\"message\":  ...ых для входа\"'\nE         - \"message\":  \"Недостаточно данных для входа\"\nE         ?           --\nE         + {\"code\":400,\"message\":\"Недостаточно данных для входа\"}\nE         ? ++++++++++++                                         +\n\ntests\\test_courier_login.py:38: AssertionError"}, "description": "Negative test of the endpoint \"Логин курьера в системе\" POST /api/v1/courier/login.Parameterized test, checks impossibility of authorization when any of the mandatory fields is missing", "parameters": [{"name": "missing_field", "value": "'login'"}], "start": 1698928028256, "stop": 1698928028647, "uuid": "27bdb97e-a7ce-4bd5-84c6-6377ad6a92bc", "historyId": "7508443dcd5241cf956084cec0c69ef0", "testCaseId": "45afb257416271363439351dc062b346", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_with_any_missing_field_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "Airforce3"}, {"name": "thread", "value": "13800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}